### ISSUE TITLE
Liaise with Kit Team about moving ansible repository to SR GitHub org

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/infrastructure-team-minutes#15]
From https://github.com/srobo/infrastructure-team-minutes/blob/master/2021/2022-01-19.md#action-points

**Comment by PeterJCLaw** [comment]
@RealOrangeOne is there any update on this?

**Comment by RealOrangeOne** [comment]
Looks like this has been done https://github.com/srobo/kit-ansible
