### ISSUE TITLE
Reach out to the competition team about competitor Discord MFA

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/infrastructure-team-minutes#34]
From https://github.com/srobo/infrastructure-team-minutes/blob/main/2023/2023-07-19.md#specific

**Comment by PeterJCLaw** [comment]
@sedders123 did this happen at all? If not, I'm happy to take this.

**Comment by sedders123** [comment]
Apologies this did not, if you're happy to take it on that'd be fab thanks!

**Comment by PeterJCLaw** [comment]
Have started this conversation at https://studentrobotics.slack.com/archives/CBP7UL6RG/p1697382579328579?thread_ts=1697382280.119809&cid=CBP7UL6RG

**Comment by PeterJCLaw** [comment]
Reaching out happened, discussion was had, MFA has been enabled for the groups agreed in that discussion.
