### ISSUE TITLE
GitHub Action to prepare SRAWN posts from the collection issues

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/infrastructure-team-minutes#35]
From https://github.com/srobo/infrastructure-team-minutes/blob/main/2023/2023-07-19.md#specific

**Comment by sedders123** [comment]
Went a little overboard and made https://srawn.jss.sh/ (https://github.com/sedders123/srawn-editor) which can edit SR(A)WN issues and then create a new file in the repo ready for PR
